### ISSUE TITLE
Insufficient color palets or just and algorythm?

### ISSUE THREAD

**Issue by fernandoG494** [Wolfteinter/Pic2Hubble#8]
Hello guys! First of all I want to congratulate you for the progress in the app, it is a really good practice for those who are interested in image analysis and pattern recognition.
Making a few attempts trying different kind of images I notice that in clear colors or in a white-bassed paletts the colors are limited. I know that is because ths most part of the base dataset are taked in outerspace-based pictures, so that have a lot of sense that the pictures and the algorythm recognice dark-based colors and the same have some confussion in white-bassed colors.

![42714a396172263db825c7cc00c0854b](https://user-images.githubusercontent.com/42920098/165027044-aeb12b26-2273-4294-92f6-2d51baa81224.jpg)
![descarga](https://user-images.githubusercontent.com/42920098/165027055-e61828a4-78fe-4f74-827f-c3e38a8e7645.jpg)

But, beside that I notice that actually the colors in the first interpretation are the corrects in the most part of the image. I have two questions: the first one is what kind of technique are you using to "classificate" the color pathern?

And the other one is about the dataset, do you normalize the potential pixel areas? I mean, do you have a default chromatic scale to translate the area of the picture to the "most near classification colour"?

I think that the both are really good aspects that you can consider for next improves. Anywho is a really good app and hope to see how this improves.

Cheers!

**Comment by Wolfteinter** [comment]
To answer your questions, the current algorithm is based on Euclidean distance, selecting the closest mean colors from the data set (previously calculated means) and the mean color of a 16 x 16 slice, we are now working on a new different approach to find the closest mean color using DFS search, the algorithm is almost complete also compute a filter to the existing data set in order to increase the variability of the colors and other ideas, if you are interested we can schedule a meeting to talk about it and consider other approaches as well.

**Comment by dbetm** [comment]
Thank you, @fernandoG494 we have a new version of the algo, we hope to deploy soon the new  and better version.
